version: '3.7'

services:
  solr:
    image: solr:7.7.2
    container_name: opus4-solr
    volumes:
      - ./opus4-search:/opt/solr/server/solr/mycores/opus4
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - opus4
    networks:
      opus4_net:
        ipv4_address: 172.19.1.100
  db:
    image: mysql:5.7.26
    container_name: opus4-db
    volumes:
      - ./mysql-data:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: opus4
      MYSQL_DATABASE: opus4db
      MYSQL_USER: opus4
      MYSQL_PASSWORD: opus4
    ports:
      - "3306:3306"
    networks:
      opus4_net:
        ipv4_address: 172.19.1.150
  web:
    image: ubuntu:19.04 
    container_name: opus4-webapp
    depends_on:
      - solr
      - db
    volumes:
      - ./application:/var/local/opus4:cached
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    networks:
      opus4_net:
        ipv4_address: 172.19.1.200
networks:
  opus4_net:
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
